appName: "@description@"
version: "@project.version@"
envTarget: "@spring.profiles.active@"

# Spring Boot configuration
spring:
  profiles:
    active: development
  application:
    name: Currency_Converter-Server
  # Database
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console.enabled: true

  # JPA properties
  jpa:
    show-sql: true
    database: h2
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
# Server configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 30
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800
async:
  core-pool-size: 2
  max-pool-size: 50
  queue-capacity: 10000

rapidapi:
  host: "currency-exchange.p.rapidapi.com"
  #IST TEMP KEY
  key: "83f4dfc1c5msh9d76a4686489828p1f4e35jsn4fbff9b62181"